import type { DemoActivity, DemoCommunity } from "./types";

/**
 * SIMULATED PRISHTINA 2036 DEMO DATA.
 *
 * Every person, organization, activity, and count below is fictional and
 * internally consistent for demonstration purposes only. Nothing here
 * represents a real municipal finding, a real organization, or a real
 * resident of Kosovo. See docs/DEMO_DATA.md for the full provenance note.
 */

export const DEMO_DATA_LABEL_SQ = "Demonstrim i simuluar — Prishtina 2036";
export const DEMO_DATA_LABEL_EN = "Simulated Prishtina 2036 demo data";

export const COMMUNITIES: DemoCommunity[] = [
  {
    id: "com-ai-club",
    slug: "prishtina-ai-klub",
    name: "Prishtina AI Klub",
    category: "technology",
    descriptionSq:
      "Një komunitet studentësh dhe profesionistësh që eksplorojnë inteligjencën artificiale përmes projekteve praktike javore.",
    description:
      "A community of students and professionals exploring artificial intelligence through hands-on weekly projects.",
    memberCount: 128,
    areaSq: "Prishtinë — Qendër",
  },
  {
    id: "com-environment",
    slug: "gjelber-per-prishtinen",
    name: "Gjelbër për Prishtinën",
    category: "environment",
    descriptionSq:
      "Grup fqinjësh dhe vullnetarësh që kujdesen për hapësirat publike të gjelbra dhe organizojnë pastrime periodike.",
    description:
      "A neighborhood and volunteer group caring for public green spaces and organizing periodic clean-up projects.",
    memberCount: 76,
    areaSq: "Prishtinë — Dardania",
  },
  {
    id: "com-youth-basketball",
    slug: "rinia-basketboll-lakrishte",
    name: "Rinia Basketboll Lakrishtë",
    category: "sports",
    descriptionSq:
      "Komunitet i të rinjve që organizon ndeshje dhe stërvitje basketbolli falas çdo javë.",
    description:
      "A youth community organizing free weekly basketball matches and practice sessions.",
    memberCount: 54,
    areaSq: "Prishtinë — Lakrishtë",
  },
  {
    id: "com-culture-collective",
    slug: "kolektivi-kulturor-prizreni-i-vjeter",
    name: "Kolektivi Kulturor Sunny Hill",
    category: "culture",
    descriptionSq:
      "Kolektiv artistësh dhe muzikantësh lokal që organizon mbrëmje kulturore mujore të hapura për të gjithë.",
    description:
      "A local collective of artists and musicians hosting open monthly cultural evenings.",
    memberCount: 91,
    areaSq: "Prishtinë — Sunny Hill",
  },
  {
    id: "com-cycling",
    slug: "prishtina-bicikleta",
    name: "Prishtina Cycling Collective",
    category: "sports",
    descriptionSq:
      "Çiklistë të të gjitha moshave që organizojnë ecje të sigurta me biçikletë dhe kërkojnë korsi më të sigurta në qytet.",
    description:
      "Riders of all ages organizing safe group rides and asking for safer bike routes across the city.",
    memberCount: 63,
    areaSq: "Prishtinë — Ulpiana",
  },
  {
    id: "com-kitchen",
    slug: "kuzhina-e-perbashket",
    name: "Community Kitchen Prishtina",
    category: "community",
    descriptionSq:
      "Fqinjë që gatuajnë dhe hanë bashkë çdo javë, me çmim të ulët, për të ndërtuar lidhje mes lagjeve.",
    description:
      "Neighbors who cook and eat together every week at a low price, building ties between neighborhoods.",
    memberCount: 47,
    areaSq: "Prishtinë — Sunny Hill",
  },
  {
    id: "com-books",
    slug: "rrethi-i-librit",
    name: "Book & Language Circle",
    category: "education",
    descriptionSq:
      "Rreth leximi dhe praktikimi i gjuhëve ku çdo kush mund të bashkohet, në shqip dhe anglisht.",
    description:
      "A reading and language-practice circle open to everyone, in Albanian and English.",
    memberCount: 39,
    areaSq: "Prishtinë — Qendër",
  },
];

export const ACTIVITIES: DemoActivity[] = [
  {
    id: "act-ai-workshop",
    slug: "punetori-ai-fillestare",
    title: "Beginner AI & Python Workshop",
    titleSq: "Punëtori Fillestare — AI dhe Python",
    summary: "A hands-on Saturday workshop for anyone curious about programming and AI.",
    summarySq: "Punëtori praktike e së shtunës për këdo kurioz rreth programimit dhe AI-së.",
    category: "technology",
    interestTags: ["technology", "education", "science"],
    areaSq: "Prishtinë — Qendër",
    areaEn: "Prishtina — Center",
    venueName: "Qendra Rinore Prishtina",
    lat: 42.6653,
    lng: 21.1622,
    date: "2036-06-13",
    startTime: "11:00",
    timezone: "Europe/Prishtina",
    capacity: 20,
    rsvpCount: 12,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible", "quiet-space-available"],
    ageEligibility: "all-ages",
    difficulty: "beginner",
    organizer: { id: "org-ai-club", name: "Prishtina AI Klub", verified: true },
    communitySlug: "prishtina-ai-klub",
    description:
      "No experience required. Bring a laptop if you have one — a limited number of loaner devices are available. We'll build a small Python project together and talk about what a career or hobby in AI could look like.",
    descriptionSq:
      "Nuk kërkohet përvojë paraprake. Sillni laptopin tuaj nëse keni — ka një numër të kufizuar pajisjesh për huazim. Do të ndërtojmë së bashku një projekt të vogël në Python dhe do të flasim se si mund të duket një karrierë apo hobi në AI.",
  },
  {
    id: "act-park-cleanup",
    slug: "pastrim-parku-gjelber",
    title: "Neighborhood Green Space Clean-Up",
    titleSq: "Pastrimi i Hapësirës së Gjelbër të Lagjes",
    summary: "Join neighbors for a Saturday morning clean-up and tree-care session.",
    summarySq: "Bashkohuni me fqinjët për një pastrim të së shtunës në mëngjes dhe kujdes për pemët.",
    category: "environment",
    interestTags: ["environment", "volunteering"],
    areaSq: "Prishtinë — Dardania",
    areaEn: "Prishtina — Dardania",
    venueName: "Parku i Lagjes Dardania",
    lat: 42.6535,
    lng: 21.1553,
    date: "2036-06-14",
    startTime: "09:00",
    timezone: "Europe/Prishtina",
    capacity: 30,
    rsvpCount: 19,
    cost: "free",
    indoor: false,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-environment", name: "Gjelbër për Prishtinën", verified: true },
    communitySlug: "gjelber-per-prishtinen",
    description:
      "Gloves, bags, and tools are provided. This session directly supports the community's ongoing park-care project — see the Projects tab on the community page for the running volunteer count.",
    descriptionSq:
      "Sigurohen doreza, qese dhe vegla. Ky aktivitet mbështet drejtpërdrejt projektin e vazhdueshëm të kujdesit për parkun — shihni skedën Projekte në faqen e komunitetit për numrin e vullnetarëve.",
  },
  {
    id: "act-basketball-pickup",
    slug: "basketboll-i-hapur-lakrishte",
    title: "Open Pick-Up Basketball",
    titleSq: "Basketboll i Hapur",
    summary: "Casual weekly pick-up games, all skill levels welcome.",
    summarySq: "Ndeshje javore rastësore, mirëpriten të gjitha nivelet.",
    category: "sports",
    interestTags: ["sports"],
    areaSq: "Prishtinë — Lakrishtë",
    areaEn: "Prishtina — Lakrishtë",
    venueName: "Fusha e Hapur e Basketbollit, Lakrishtë",
    lat: 42.6701,
    lng: 21.1489,
    date: "2036-06-13",
    startTime: "18:00",
    timezone: "Europe/Prishtina",
    capacity: 16,
    rsvpCount: 16,
    cost: "free",
    indoor: false,
    accessibility: [],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-basketball", name: "Rinia Basketboll Lakrishtë", verified: false },
    communitySlug: "rinia-basketboll-lakrishte",
    description:
      "This session is at capacity — you can join the waiting list and you'll be notified if a spot opens up. New weekly sessions are posted every Monday.",
    descriptionSq:
      "Ky aktivitet ka arritur kapacitetin — mund të bashkoheni në listën e pritjes dhe do të njoftoheni nëse hapet një vend. Aktivitete të reja javore publikohen çdo të hënë.",
  },
  {
    id: "act-culture-evening",
    slug: "mbremje-kulturore-sunny-hill",
    title: "Open Cultural Evening",
    titleSq: "Mbrëmje Kulturore e Hapur",
    summary: "Local music, poetry, and short film — an informal monthly gathering.",
    summarySq: "Muzikë lokale, poezi dhe film i shkurtër — takim joformal mujor.",
    category: "culture",
    interestTags: ["culture", "music", "art", "books"],
    areaSq: "Prishtinë — Sunny Hill",
    areaEn: "Prishtina — Sunny Hill",
    venueName: "Salla Komunitare Sunny Hill",
    lat: 42.6482,
    lng: 21.1701,
    date: "2036-06-20",
    startTime: "19:30",
    timezone: "Europe/Prishtina",
    capacity: 60,
    rsvpCount: 33,
    cost: "paid",
    costDetail: "€2 suggested donation at the door",
    indoor: true,
    accessibility: ["wheelchair-accessible", "captioned"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-culture", name: "Kolektivi Kulturor Sunny Hill", verified: true },
    communitySlug: "kolektivi-kulturor-prizreni-i-vjeter",
    description:
      "An open mic slot is available — sign up at the door. Performances are typically in Albanian with informal English translation offered by attendees.",
    descriptionSq:
      "Ka një vend të lirë për \"open mic\" — regjistrohuni në hyrje. Performancat zakonisht janë në shqip, me përkthim joformal në anglisht nga pjesëmarrësit.",
  },
  {
    id: "act-coding-teens",
    slug: "kodim-per-adoleshente",
    title: "Coding Club for Teens (Supervised)",
    titleSq: "Klub Kodimi për Adoleshentë (i Mbikëqyrur)",
    summary: "A supervised, school-linked coding club for ages 13–17.",
    summarySq: "Klub kodimi i mbikëqyrur, i lidhur me shkollën, për moshat 13–17.",
    category: "technology",
    interestTags: ["technology", "education", "gaming"],
    areaSq: "Prishtinë — Dardania",
    areaEn: "Prishtina — Dardania",
    venueName: "Shkolla e Mesme 'Xhevdet Doda' — Salla e TI",
    lat: 42.6558,
    lng: 21.1602,
    date: "2036-06-17",
    startTime: "15:00",
    timezone: "Europe/Prishtina",
    capacity: 18,
    rsvpCount: 10,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "supervised-minors",
    difficulty: "beginner",
    organizer: { id: "org-ai-club", name: "Prishtina AI Klub", verified: true },
    communitySlug: "prishtina-ai-klub",
    description:
      "Runs with a school staff supervisor present at every session. Registration requires a guardian's confirmation; there is no open messaging between participants and adult organizers outside the supervised session.",
    descriptionSq:
      "Zhvillohet gjithmonë me praninë e një stafi mbikëqyrës të shkollës. Regjistrimi kërkon konfirmimin e prindit/kujdestarit; nuk ka komunikim të hapur mes pjesëmarrësve dhe organizatorëve të rritur jashtë sesionit të mbikëqyrur.",
  },
  {
    id: "act-photography-walk",
    slug: "shetitje-fotografike-qender",
    title: "Golden Hour Photography Walk",
    titleSq: "Shëtitje Fotografike në \"Orën e Artë\"",
    summary: "A relaxed walk through the city center for photography enthusiasts.",
    summarySq: "Një shëtitje e qetë nëpër qendër të qytetit për dashamirësit e fotografisë.",
    category: "culture",
    interestTags: ["photography", "art", "travel"],
    areaSq: "Prishtinë — Qendër",
    areaEn: "Prishtina — Center",
    venueName: "Sheshi Nënë Tereza",
    lat: 42.6621,
    lng: 21.1631,
    date: "2036-06-21",
    startTime: "19:00",
    timezone: "Europe/Prishtina",
    capacity: 15,
    rsvpCount: 6,
    cost: "free",
    indoor: false,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-culture", name: "Kolektivi Kulturor Sunny Hill", verified: true },
    communitySlug: "kolektivi-kulturor-prizreni-i-vjeter",
    description:
      "Any camera welcome, including phones. We'll end at a nearby café for an informal photo share — attendance there is optional.",
    descriptionSq:
      "Mirëpritet çdo kamerë, përfshirë telefonat. Do të përfundojmë në një kafiteri aty pranë për shpërndarje joformale të fotove — pjesëmarrja atje është opsionale.",
  },
  {
    id: "act-family-bike-ride",
    slug: "ecje-me-biciklete-ulpiana",
    title: "Sunday Family Bike Ride",
    titleSq: "Ecje e së Dielës me Biçikletë për Familje",
    summary: "A gentle 12 km group ride on the safest routes, with a café stop halfway.",
    summarySq: "Një ecje e qetë 12 km në grup, nëpër rrugët më të sigurta, me ndalesë kafeje në mes.",
    category: "sports",
    interestTags: ["sports", "travel", "environment"],
    areaSq: "Prishtinë — Ulpiana",
    areaEn: "Prishtina — Ulpiana",
    venueName: "Sheshi i Ulpianës (pika e nisjes)",
    lat: 42.6489,
    lng: 21.1408,
    date: "2036-06-22",
    startTime: "10:00",
    timezone: "Europe/Prishtina",
    capacity: 25,
    rsvpCount: 11,
    cost: "free",
    indoor: false,
    accessibility: [],
    ageEligibility: "all-ages",
    difficulty: "beginner",
    organizer: { id: "org-cycling", name: "Prishtina Cycling Collective", verified: true },
    communitySlug: "prishtina-bicikleta",
    description:
      "Helmets are required; a few loaner bikes are available if you tell us in advance. The pace is set by the slowest rider — nobody gets left behind.",
    descriptionSq:
      "Kaska është e detyrueshme; ka disa biçikleta për huazim nëse na njoftoni paraprakisht. Ritmi përcaktohet nga çiklisti më i ngadalshëm — askush nuk mbetet pas.",
  },
  {
    id: "act-community-dinner",
    slug: "darke-e-perbashket-sunny-hill",
    title: "Community Kitchen: Shared Dinner",
    titleSq: "Kuzhina e Përbashkët: Darkë Bashkë",
    summary: "Cook and eat a vegetarian dinner with neighbors — everyone helps, everyone eats.",
    summarySq: "Gatuani dhe hani një darkë vegjetariane me fqinjët — të gjithë ndihmojnë, të gjithë hanë.",
    category: "community",
    interestTags: ["cooking", "volunteering", "culture"],
    areaSq: "Prishtinë — Sunny Hill",
    areaEn: "Prishtina — Sunny Hill",
    venueName: "Salla Komunitare Sunny Hill — Kuzhina",
    lat: 42.6479,
    lng: 21.1695,
    date: "2036-06-19",
    startTime: "18:30",
    timezone: "Europe/Prishtina",
    capacity: 30,
    rsvpCount: 14,
    cost: "paid",
    costDetail: "€3 covers ingredients",
    indoor: true,
    accessibility: ["wheelchair-accessible", "quiet-space-available"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-kitchen", name: "Community Kitchen Prishtina", verified: true },
    communitySlug: "kuzhina-e-perbashket",
    description:
      "Tell us about allergies when you RSVP. Older neighbors eat free — the small contribution from everyone else covers them.",
    descriptionSq:
      "Na tregoni për alergjitë kur bëni RSVP. Fqinjët e moshuar hanë falas — kontributi i vogël i të tjerëve i mbulon.",
  },
  {
    id: "act-book-circle",
    slug: "rrethi-i-librit-shqip-anglisht",
    title: "Book & Language Circle",
    titleSq: "Rrethi i Librit dhe Gjuhëve",
    summary: "Read a short story aloud in Albanian and English, then chat over tea.",
    summarySq: "Lexoni një tregim të shkurtër me zë të lartë në shqip dhe anglisht, pastaj bisedoni me çaj.",
    category: "education",
    interestTags: ["books", "education", "culture"],
    areaSq: "Prishtinë — Qendër",
    areaEn: "Prishtina — Center",
    venueName: "Biblioteka e Qytetit — Salla e Leximit",
    lat: 42.6608,
    lng: 21.1652,
    date: "2036-06-18",
    startTime: "17:30",
    timezone: "Europe/Prishtina",
    capacity: 14,
    rsvpCount: 6,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible", "quiet-space-available", "captioned"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-books", name: "Book & Language Circle", verified: true },
    communitySlug: "rrethi-i-librit",
    description:
      "The text is chosen a week ahead and shared here. No preparation is required — you can just listen.",
    descriptionSq:
      "Teksti zgjidhet një javë përpara dhe ndahet këtu. Nuk kërkohet përgatitje — mund të dëgjoni thjesht.",
  },
  {
    id: "act-civic-data-night",
    slug: "nate-e-te-dhenave-qytetare",
    title: "Civic Data Night",
    titleSq: "Nata e të Dhënave Qytetare",
    summary: "Explore open city data with Python and build a small chart for your neighborhood.",
    summarySq: "Eksploroni të dhënat e hapura të qytetit me Python dhe ndërtoni një grafik për lagjen tuaj.",
    category: "technology",
    interestTags: ["technology", "science", "entrepreneurship"],
    areaSq: "Prishtinë — Qendër",
    areaEn: "Prishtina — Center",
    venueName: "Qendra Rinore Prishtina — Laboratori",
    lat: 42.6653,
    lng: 21.1622,
    date: "2036-06-24",
    startTime: "18:00",
    timezone: "Europe/Prishtina",
    capacity: 24,
    rsvpCount: 9,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "adults-only",
    difficulty: "intermediate",
    organizer: { id: "org-ai-club", name: "Prishtina AI Klub", verified: true },
    communitySlug: "prishtina-ai-klub",
    description:
      "Some Python basics help but pairs are formed on the night. All datasets are fictional demo data.",
    descriptionSq:
      "Njohuritë bazë të Python ndihmojnë, por çiftet formohen në mbrëmje. Të gjitha të dhënat janë demonstruese dhe fiktive.",
  },
  {
    id: "act-phone-photo-workshop",
    slug: "punetori-fotografie-me-telefon",
    title: "Phone Photography Workshop",
    titleSq: "Punëtori Fotografie me Telefon",
    summary: "Learn light, framing and editing with the camera already in your pocket.",
    summarySq: "Mësoni dritën, kuadrimin dhe redaktimin me kamerën që keni tashmë në xhep.",
    category: "culture",
    interestTags: ["photography", "art", "travel"],
    areaSq: "Prishtinë — Sunny Hill",
    areaEn: "Prishtina — Sunny Hill",
    venueName: "Salla Komunitare Sunny Hill",
    lat: 42.6482,
    lng: 21.1701,
    date: "2036-06-28",
    startTime: "11:00",
    timezone: "Europe/Prishtina",
    capacity: 12,
    rsvpCount: 5,
    cost: "paid",
    costDetail: "€5 to cover materials",
    indoor: true,
    accessibility: ["wheelchair-accessible", "captioned"],
    ageEligibility: "all-ages",
    difficulty: "beginner",
    organizer: { id: "org-culture", name: "Kolektivi Kulturor Sunny Hill", verified: true },
    communitySlug: "kolektivi-kulturor-prizreni-i-vjeter",
    description:
      "Bring any smartphone. We finish with a short walk to practice what we learned; photos stay yours.",
    descriptionSq:
      "Sillni çfarëdo telefoni. Përfundojmë me një shëtitje të shkurtër për të praktikuar; fotot mbeten tuajat.",
  },
  {
    id: "act-tree-planting",
    slug: "mbjellja-e-pemeve-dardania",
    title: "Tree Planting Morning",
    titleSq: "Mëngjes Mbjelljeje Pemësh",
    summary: "Plant native saplings along the Dardania green corridor before the summer heat.",
    summarySq: "Mbillni fidane vendase përgjatë korridorit të gjelbër të Dardanisë para vapës së verës.",
    category: "environment",
    interestTags: ["environment", "volunteering", "sports"],
    areaSq: "Prishtinë — Dardania",
    areaEn: "Prishtina — Dardania",
    venueName: "Korridori i Gjelbër, Dardania",
    lat: 42.6549,
    lng: 21.1541,
    date: "2036-06-22",
    startTime: "08:30",
    timezone: "Europe/Prishtina",
    capacity: 40,
    rsvpCount: 22,
    cost: "free",
    indoor: false,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-environment", name: "Gjelbër për Prishtinën", verified: true },
    communitySlug: "gjelber-per-prishtinen",
    description:
      "Tools and water are provided. Kids can help with watering. This session feeds the park-care volunteer project.",
    descriptionSq:
      "Veglat dhe uji sigurohen. Fëmijët mund të ndihmojnë në ujitje. Ky sesion ushqen projektin vullnetar të kujdesit për parkun.",
  },
  {
    id: "act-3x3-tournament",
    slug: "turne-basketbolli-3x3",
    title: "3×3 Street Basketball Tournament",
    titleSq: "Turne Basketbolli 3×3 në Rrugë",
    summary: "Friendly 3×3 bracket for mixed teams — come with friends or get matched on the day.",
    summarySq: "Turne miqësor 3×3 me ekipe të përziera — ejani me shokë ose caktoheni në vend.",
    category: "sports",
    interestTags: ["sports"],
    areaSq: "Prishtinë — Lakrishtë",
    areaEn: "Prishtina — Lakrishtë",
    venueName: "Fusha e Hapur e Basketbollit, Lakrishtë",
    lat: 42.6701,
    lng: 21.1489,
    date: "2036-06-28",
    startTime: "16:00",
    timezone: "Europe/Prishtina",
    capacity: 32,
    rsvpCount: 30,
    cost: "free",
    indoor: false,
    accessibility: [],
    ageEligibility: "all-ages",
    difficulty: "intermediate",
    organizer: { id: "org-basketball", name: "Rinia Basketboll Lakrishtë", verified: false },
    communitySlug: "rinia-basketboll-lakrishte",
    description:
      "Only two spots left. Games are 10 minutes; referees are volunteers. Bring water.",
    descriptionSq:
      "Kanë mbetur vetëm dy vende. Ndeshjet zgjasin 10 minuta; gjyqtarët janë vullnetarë. Sillni ujë.",
  },
  {
    id: "act-poetry-music-night",
    slug: "mbremje-poezie-dhe-muzike",
    title: "Poetry & Live Music Night",
    titleSq: "Mbrëmje Poezie dhe Muzike Live",
    summary: "Local poets and a small acoustic band, with captions projected for every piece.",
    summarySq: "Poetë lokalë dhe një grup i vogël akustik, me titra të projektuara për çdo pjesë.",
    category: "culture",
    interestTags: ["music", "books", "culture", "art"],
    areaSq: "Prishtinë — Sunny Hill",
    areaEn: "Prishtina — Sunny Hill",
    venueName: "Salla Komunitare Sunny Hill",
    lat: 42.6482,
    lng: 21.1701,
    date: "2036-06-27",
    startTime: "20:00",
    timezone: "Europe/Prishtina",
    capacity: 50,
    rsvpCount: 21,
    cost: "paid",
    costDetail: "€4 suggested donation",
    indoor: true,
    accessibility: ["wheelchair-accessible", "captioned", "quiet-space-available"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-culture", name: "Kolektivi Kulturor Sunny Hill", verified: true },
    communitySlug: "kolektivi-kulturor-prizreni-i-vjeter",
    description:
      "A quiet room is available next door for anyone who needs a break from the sound.",
    descriptionSq:
      "Një sallë e qetë është në dispozicion aty pranë për këdo që ka nevojë për pushim nga zëri.",
  },
  {
    id: "act-family-robotics",
    slug: "robotike-per-familje",
    title: "Family Robotics Saturday",
    titleSq: "E Shtunë Robotike për Familje",
    summary: "Build and program a small wheeled robot together — parents and kids on the same team.",
    summarySq: "Ndërtoni dhe programoni së bashku një robot të vogël — prindër dhe fëmijë në të njëjtin ekip.",
    category: "technology",
    interestTags: ["technology", "education", "science", "gaming"],
    areaSq: "Prishtinë — Qendër",
    areaEn: "Prishtina — Center",
    venueName: "Qendra Rinore Prishtina",
    lat: 42.6653,
    lng: 21.1622,
    date: "2036-06-21",
    startTime: "10:00",
    timezone: "Europe/Prishtina",
    capacity: 20,
    rsvpCount: 8,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible", "quiet-space-available"],
    ageEligibility: "all-ages",
    difficulty: "beginner",
    organizer: { id: "org-ai-club", name: "Prishtina AI Klub", verified: true },
    communitySlug: "prishtina-ai-klub",
    description:
      "Children attend with a parent or guardian at all times. No prior experience needed.",
    descriptionSq:
      "Fëmijët ndjekin gjithmonë me prindin ose kujdestarin. Nuk kërkohet përvojë paraprake.",
  },
  {
    id: "act-ecotech-lab",
    slug: "laborator-ideshe-eko-teknologji",
    title: "Eco-Tech Idea Lab — BRIDGE kickoff",
    titleSq: "Laborator Idesh Eko-Teknologji — nisja e BRIDGE",
    summary: "The first joint session of the AI club and the green group: sensors, apps and volunteers for Dardania's park.",
    summarySq: "Sesioni i parë i përbashkët i AI klubit dhe grupit të gjelbër: sensorë, aplikacione dhe vullnetarë për parkun e Dardanisë.",
    category: "technology",
    interestTags: ["technology", "environment", "volunteering", "science"],
    areaSq: "Prishtinë — Dardania",
    areaEn: "Prishtina — Dardania",
    venueName: "Shkolla e Mesme 'Xhevdet Doda' — Salla e TI",
    lat: 42.6558,
    lng: 21.1602,
    date: "2036-06-25",
    startTime: "18:00",
    timezone: "Europe/Prishtina",
    capacity: 25,
    rsvpCount: 10,
    cost: "free",
    indoor: true,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "adults-only",
    difficulty: "all-levels",
    organizer: { id: "org-ai-club", name: "Prishtina AI Klub", verified: true },
    communitySlug: "prishtina-ai-klub",
    description:
      "This is the kickoff of the accepted BRIDGE collaboration between Prishtina AI Klub and Gjelbër për Prishtinën. Volunteers from both communities scope the first prototype for the Dardania park need.",
    descriptionSq:
      "Ky është nisja e bashkëpunimit BRIDGE të pranuar mes Prishtina AI Klub dhe Gjelbër për Prishtinën. Vullnetarët nga të dy komunitetet përcaktojnë prototipin e parë për nevojën e parkut në Dardani.",
  },
  {
    id: "act-germia-walk",
    slug: "shetitje-natyrore-germia",
    title: "Germia Park Nature Walk",
    titleSq: "Shëtitje Natyrore në Parkun e Gjermisë",
    summary: "A moderate 6 km forest walk with a guide who explains the local plants and birds.",
    summarySq: "Një shëtitje mesatare 6 km në pyll me udhëzues që shpjegon bimët dhe zogjtë vendas.",
    category: "environment",
    interestTags: ["environment", "travel", "photography", "sports"],
    areaSq: "Prishtinë — Gërmia",
    areaEn: "Prishtina — Germia",
    venueName: "Hyrja kryesore e Parkut të Gjermisë",
    lat: 42.6741,
    lng: 21.2335,
    date: "2036-06-29",
    startTime: "09:00",
    timezone: "Europe/Prishtina",
    capacity: 30,
    rsvpCount: 12,
    cost: "free",
    indoor: false,
    accessibility: [],
    ageEligibility: "all-ages",
    difficulty: "intermediate",
    organizer: { id: "org-environment", name: "Gjelbër për Prishtinën", verified: true },
    communitySlug: "gjelber-per-prishtinen",
    description:
      "Uneven forest paths — not suitable for wheelchairs. Wear sturdy shoes and bring water.",
    descriptionSq:
      "Shtigje të pabarabarta pyjore — nuk janë të përshtatshme për karroca. Vishni këpucë të forta dhe sillni ujë.",
  },
  {
    id: "act-makers-market",
    slug: "pazar-i-hapur-lokal",
    title: "Local Makers Market",
    titleSq: "Pazari Lokal i Krijuesve",
    summary: "Stalls of local food, crafts and second-hand books — bring a bag, meet your neighbors.",
    summarySq: "Stenda me ushqim lokal, zanate dhe libra të përdorur — sillni një çantë, takoni fqinjët.",
    category: "community",
    interestTags: ["cooking", "entrepreneurship", "art", "books"],
    areaSq: "Prishtinë — Sunny Hill",
    areaEn: "Prishtina — Sunny Hill",
    venueName: "Sheshi pranë Sallës Komunitare Sunny Hill",
    lat: 42.6476,
    lng: 21.1708,
    date: "2036-06-21",
    startTime: "12:00",
    timezone: "Europe/Prishtina",
    capacity: 100,
    rsvpCount: 40,
    cost: "free",
    indoor: false,
    accessibility: ["wheelchair-accessible"],
    ageEligibility: "all-ages",
    difficulty: "all-levels",
    organizer: { id: "org-kitchen", name: "Community Kitchen Prishtina", verified: true },
    communitySlug: "kuzhina-e-perbashket",
    description:
      "Entry is free. Stall holders are local demo makers; nothing is sold in this prototype.",
    descriptionSq:
      "Hyrja është falas. Shitësit janë krijues lokalë demonstrues; në këtë prototip nuk shitet asgjë.",
  },
];

export function getActivityBySlug(slug: string): DemoActivity | undefined {
  return ACTIVITIES.find((a) => a.slug === slug);
}

export function getCommunityBySlug(slug: string): DemoCommunity | undefined {
  return COMMUNITIES.find((c) => c.slug === slug);
}
